spring:
  application:
    name: inventory-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_ISSUER_URI:http://localhost:8180/realms/reservation}
          jwk-set-uri: ${SECURITY_JWK_SET_URI:http://localhost:8180/realms/reservation/protocol/openid-connect/certs}
          audiences: inventory-api

server:
  port: 8081

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi/inventory.yaml
    disable-swagger-default-url: true
    oauth:
      client-id: reservation-swagger
      scopes: inventory-api
      use-pkce-with-authorization-code-grant: true
