spring:
  application:
    name: inventory-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/inventory}
    username: ${DB_USERNAME:inventory}
    password: ${DB_PASSWORD:inventory}
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_ISSUER_URI:http://localhost:8180/realms/reservation}
          jwk-set-uri: ${SECURITY_JWK_SET_URI:http://localhost:8180/realms/reservation/protocol/openid-connect/certs}
          audiences: inventory-api

server:
  port: 8081

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /openapi/inventory.yaml
    disable-swagger-default-url: true
    oauth:
      client-id: reservation-swagger
      scopes: inventory-api
      use-pkce-with-authorization-code-grant: true
